"""
schema_consolidado.py — Paso 1.0
Define las ~126 columnas del Consolidado con sus metadatos.
Output: UNIFICADO/output/schema_consolidado.csv
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from utils import *
import pandas as pd

SCHEMA = [
    # === IDENTIFICACION (4) ===
    {"variable": "iso3", "tipo": "string", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Codigo ISO 3166-1 alpha-3 del pais"},
    {"variable": "entity_type", "tipo": "string", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Tipo de entidad: pais, region"},
    {"variable": "pais_original", "tipo": "string", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Nombre exacto del pais en el Excel fuente de ese ano"},
    {"variable": "year", "tipo": "int", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Ano del indice"},

    # === METADATOS (2) ===
    {"variable": "scale", "tipo": "string", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Escala del total_score: 0-10 (2019) o 0-100 (2020-2025)"},
    {"variable": "framework", "tipo": "string", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Framework usado: 4_clusters, 3_pillars_10_dims, 6_pillars_14_dims"},

    # === SCORE PRINCIPAL (1) ===
    {"variable": "total_score", "tipo": "float", "anos": "2019-2025",
     "framework": "todos", "descripcion": "Puntaje indice de preparacion gubernamental para IA. Escala 0-10 (2019) o 0-100 (2020-2025)"},

    # === RANKING GLOBAL (1) ===
    {"variable": "rank", "tipo": "int", "anos": "2020-2025",
     "framework": "3_pillars_10_dims,6_pillars_14_dims",
     "descripcion": "Ranking global (1=mejor). No existe en 2019 en el Consolidado (ver Rankings_Regionales_2019)"},

    # === 2019: RAW INDICATORS (12) ===
    {"variable": "privacy_laws", "tipo": "int", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Leyes de privacidad: 0=no, 1=si"},
    {"variable": "ai_strategy", "tipo": "int", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Estrategia IA: 0=none, 1=forthcoming, 2=yes"},
    {"variable": "data_availability", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Disponibilidad de datos abiertos (OKFN, escala 1-100)"},
    {"variable": "govt_procurement_advanced_tech", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Compras gubernamentales de tecnologia avanzada (WEF NRI)"},
    {"variable": "data_capability_govt", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Capacidad de datos en gobierno (UN e-gov index, 0-1)"},
    {"variable": "technology_skills", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Habilidades tecnologicas (WEF GCR)"},
    {"variable": "ai_startups", "tipo": "int", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Numero de startups IA (Crunchbase, conteo directo)"},
    {"variable": "log_ai_startups", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Log de AI startups"},
    {"variable": "innovation_capability", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Capacidad de innovacion sector privado (WEF GCR)"},
    {"variable": "digital_public_services", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Servicios publicos digitales (UN e-gov, 0-1)"},
    {"variable": "govt_effectiveness", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Efectividad del gobierno (World Bank)"},
    {"variable": "ict_govt_vision", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Importancia TIC en vision de gobierno (WEF NRI)"},

    # === 2019: NORMALIZED INDICATORS (10) ===
    {"variable": "norm_privacy_laws", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Privacy laws"},
    {"variable": "norm_ai_strategy", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): AI strategy"},
    {"variable": "norm_data_availability", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Data availability"},
    {"variable": "norm_govt_procurement", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Gov't procurement"},
    {"variable": "norm_data_capability", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Data capability"},
    {"variable": "norm_technology_skills", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Technology skills"},
    {"variable": "norm_log_ai_startups", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Log AI startups"},
    {"variable": "norm_innovation_capability", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Innovation capability"},
    {"variable": "norm_digital_public_services", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Digital public services"},
    {"variable": "norm_govt_effectiveness", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): Govt effectiveness"},
    {"variable": "norm_ict_govt_vision", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Normalizado (0-1): ICT govt vision"},

    # === 2019: CLUSTER AVERAGES (4) ===
    {"variable": "avg_governance", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Promedio cluster Governance (0-1)"},
    {"variable": "avg_infrastructure_data", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Promedio cluster Infrastructure and data (0-1)"},
    {"variable": "avg_skills_education", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Promedio cluster Skills and education (0-1)"},
    {"variable": "avg_govt_public_services", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Promedio cluster Government and public services (0-1)"},

    # === 2020-2024: 3 PILLARS (3) ===
    {"variable": "government", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Pilar Government (0-100). Capacidad gubernamental para IA"},
    {"variable": "technology_sector", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Pilar Technology Sector (0-100). Madurez del ecosistema tecnologico"},
    {"variable": "data_infrastructure", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Pilar Data and Infrastructure (0-100). Datos e infraestructura"},

    # === 2020-2024: 10 DIMENSIONS (10) ===
    {"variable": "vision", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Vision (0-100). Estrategia nacional IA"},
    {"variable": "governance_ethics", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Governance and Ethics (0-100)"},
    {"variable": "digital_capacity", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Digital Capacity (0-100)"},
    {"variable": "adaptability", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Adaptability (0-100)"},
    {"variable": "size", "tipo": "float", "anos": "2020-2021",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Size (0-100, solo 2020-2021). Renombrada a maturity desde 2022"},
    {"variable": "maturity", "tipo": "float", "anos": "2022-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Maturity (0-100, desde 2022). Antes llamada Size"},
    {"variable": "innovation_capacity", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Innovation Capacity (0-100)"},
    {"variable": "human_capital", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Human Capital (0-100)"},
    {"variable": "infrastructure", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Infrastructure (0-100)"},
    {"variable": "data_availability", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Data Availability (0-100)"},
    {"variable": "data_representativeness", "tipo": "float", "anos": "2020-2024",
     "framework": "3_pillars_10_dims", "descripcion": "Dimension Data Representativeness (0-100). Tiene missing en 2020-2023"},

    # === 2024: RANKING DETAIL (1) ===
    {"variable": "ranking_detail", "tipo": "float", "anos": "2024",
     "framework": "3_pillars_10_dims", "descripcion": "Ranking dentro de detailed scores 2024. 82 missing (solo 106 paises rankeados)"},

    # === 2025: 6 PILLARS (6) ===
    {"variable": "policy_capacity", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar Policy Capacity (0-100). Capacidad de diseno politico IA"},
    {"variable": "ai_infrastructure", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar AI Infrastructure (0-100). Condiciones tecnicas para IA"},
    {"variable": "governance_2025", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar Governance (0-100). Marco de gobernanza IA (nota: distinto del pilar Government 2020-2024)"},
    {"variable": "public_sector_adoption", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar Public Sector Adoption (0-100). Adopcion IA en sector publico"},
    {"variable": "development_diffusion", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar Development and Diffusion (0-100). Desarrollo y difusion IA"},
    {"variable": "resilience", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Pilar Resilience (0-100). Resiliencia ante impactos de IA"},

    # === 2025: 14 DIMENSIONS (14) ===
    {"variable": "policy_vision", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Policy vision (0-100)"},
    {"variable": "policy_commitment", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Policy commitment (0-100)"},
    {"variable": "compute_capacity", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Compute capacity (0-100)"},
    {"variable": "enabling_technical_infrastructure", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Enabling technical infrastructure (0-100)"},
    {"variable": "data_quality", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Data quality (0-100)"},
    {"variable": "governance_principles", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Governance principles (0-100)"},
    {"variable": "regulatory_compliance", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Regulatory compliance (0-100)"},
    {"variable": "government_digital_policy", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Government digital policy (0-100)"},
    {"variable": "e_government_delivery", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension e-Government delivery (0-100)"},
    {"variable": "human_capital_2025", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Human capital (0-100). Nota: distinto de human_capital 2020-2024"},
    {"variable": "ai_sector_maturity", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension AI sector maturity (0-100)"},
    {"variable": "ai_technology_diffusion", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension AI technology diffusion (0-100)"},
    {"variable": "societal_transition", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Societal transition (0-100)"},
    {"variable": "safety_security", "tipo": "float", "anos": "2025",
     "framework": "6_pillars_14_dims", "descripcion": "Dimension Safety and security (0-100)"},

    # === 2023: 39 INDICATORS ===
    {"variable": "ind_ai_strategy", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: AI strategy (0-100, ternario)"},
    {"variable": "ind_data_protection_laws", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Data protection and privacy laws (0-100)"},
    {"variable": "ind_cybersecurity", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Cybersecurity (0-100)"},
    {"variable": "ind_regulatory_quality", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Regulatory quality (0-100)"},
    {"variable": "ind_ethical_principles", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Ethical principles (0-100, ternario)"},
    {"variable": "ind_accountability", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Accountability (0-100)"},
    {"variable": "ind_online_services", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Online services (0-100)"},
    {"variable": "ind_foundational_it", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Foundational IT infrastructure (0-100)"},
    {"variable": "ind_govt_promotion_emerging_tech", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Govt Promotion of Investment in Emerging Tech (0-100)"},
    {"variable": "ind_govt_effectiveness", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Government Effectiveness (0-100)"},
    {"variable": "ind_govt_responsiveness", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Government responsiveness to change (0-100)"},
    {"variable": "ind_procurement_data", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Procurement Data (0-100)"},
    {"variable": "ind_ai_unicorns_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Number of AI Unicorns log transformation (0-100)"},
    {"variable": "ind_non_ai_unicorns_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Number of non-AI Unicorns log transformation (0-100)"},
    {"variable": "ind_ict_trade_services_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Value of trade in ICT services per capita log (0-100)"},
    {"variable": "ind_ict_trade_goods_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Value of trade in ICT goods per capita log (0-100)"},
    {"variable": "ind_software_spending", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Computer software spending (0-100)"},
    {"variable": "ind_time_govt_regulations", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Time spent dealing with govt regulations (0-100)"},
    {"variable": "ind_vc_availability", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: VC availability (0-100)"},
    {"variable": "ind_rd_spending_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: R&D Spending log transformation (0-100)"},
    {"variable": "ind_company_investment_emerging_tech", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Company investment in emerging technology (0-100)"},
    {"variable": "ind_ai_research_papers_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: AI research papers log transformation (0-100)"},
    {"variable": "ind_stem_graduates", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Graduates in STEM or computer science (0-100)"},
    {"variable": "ind_github_activity_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Github Activity log transformation (0-100)"},
    {"variable": "ind_female_stem_graduates", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Female STEM Graduates (0-100)"},
    {"variable": "ind_eng_tech_higher_ed_quality", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Quality of Engineering and Technology Higher Ed (0-100)"},
    {"variable": "ind_ict_skills", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: ICT skills (0-100)"},
    {"variable": "ind_telecom_infrastructure", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Telecommunications Infrastructure (0-100)"},
    {"variable": "ind_supercomputers_log", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Supercomputers log transformation (0-100)"},
    {"variable": "ind_broadband_quality", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Broadband Quality (0-100)"},
    {"variable": "ind_5g_infrastructure", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: 5G Infrastructure (0-100, binario)"},
    {"variable": "ind_adoption_emerging_tech", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Adoption of Emerging Technologies (0-100)"},
    {"variable": "ind_open_data", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Open Data (0-100)"},
    {"variable": "ind_data_governance", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Data governance (0-100, ternario)"},
    {"variable": "ind_mobile_subscriptions", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Mobile-cellular telephone subscriptions (0-100)"},
    {"variable": "ind_households_internet", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Households with internet access (0-100)"},
    {"variable": "ind_statistical_capacity", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Statistical Capacity (0-100)"},
    {"variable": "ind_cost_internet_device", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Cost of cheapest internet-enabled device (0-100, invertido)"},
    {"variable": "ind_gender_gap_internet", "tipo": "float", "anos": "2023",
     "framework": "3_pillars_10_dims", "descripcion": "Indicador: Gender gap in internet access (0-100, 100=sin brecha)"},

    # === 2019: REGIONAL RANKINGS (16) ===
    {"variable": "rank_global", "tipo": "int", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking global en 2019 (hoja Rankings)"},
    {"variable": "score_global", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score global en 2019 (hoja Rankings, escala 0-10)"},
    {"variable": "rank_asia_pacific", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Asia-Pacific en 2019"},
    {"variable": "score_asia_pacific", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Asia-Pacific en 2019"},
    {"variable": "rank_africa", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Africa en 2019"},
    {"variable": "score_africa", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Africa en 2019"},
    {"variable": "rank_latam", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Latin America and Caribbean en 2019"},
    {"variable": "score_latam", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Latin America and Caribbean en 2019"},
    {"variable": "rank_north_america", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional North America en 2019"},
    {"variable": "score_north_america", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional North America en 2019"},
    {"variable": "rank_eastern_europe", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Eastern Europe en 2019"},
    {"variable": "score_eastern_europe", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Eastern Europe en 2019"},
    {"variable": "rank_australasia", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Australia/NZ en 2019"},
    {"variable": "score_australasia", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Australia/NZ en 2019"},
    {"variable": "rank_western_europe", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Ranking regional Western Europe en 2019"},
    {"variable": "score_western_europe", "tipo": "float", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Score regional Western Europe en 2019"},
    {"variable": "region_pertenece", "tipo": "string", "anos": "2019",
     "framework": "4_clusters", "descripcion": "Region a la que pertenece el pais segun Oxford Insights 2019"},
]

if __name__ == "__main__":
    df_schema = pd.DataFrame(SCHEMA)
    out_path = output_path("schema_consolidado.csv")
    df_schema.to_csv(out_path, index=False)
    print(f"Schema guardado: {out_path}")
    print(f"Total variables en schema: {len(df_schema)}")
    print(f"Columnas: {list(df_schema.columns)}")
    print(f"\nVariables por framework:")
    for fw in df_schema['framework'].unique():
        count = len(df_schema[df_schema['framework'] == fw])
        print(f"  {fw}: {count}")
